<?php

/**
 * This file is automatically generated. Use 'arc liberate' to rebuild it.
 *
 * @generated
 * @phutil-library-version 2
 */
phutil_register_library_map(array(
  '__library_version__' => 2,
  'class' => array(
    'PhabricatorScryptPasswordHasher' => 'extensions/util/password/PhabricatorScryptPasswordHasher.php',
  ),
  'function' => array(),
  'xmap' => array(
    'PhabricatorScryptPasswordHasher' => 'PhabricatorPasswordHasher',
  ),
));
